import{a as E,S as R,i as n}from"./assets/vendor-CNqCr-V-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const $="53143785-3d26ca9fafc478fbd760d25ea",A="https://pixabay.com/api/";async function L(e,r=1,i=15){try{const s={key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:i},{data:t}=await E.get(A,{params:s});return t}catch(s){throw s}}function w(e){return e.map(({webformatURL:r,largeImageURL:i,tags:s,likes:t,views:o,comments:c,downloads:q})=>`
  <li class="gallery-item">
    <div class="photo-card">
      <a href="${i}" data-caption="${s}" class="img-link"><img src="${r}" alt="${s}" loading="lazy" /></a>
      <ul class="image-stats">
        <li><span>Likes:</span> ${t}</li>
        <li><span>Views:</span> ${o}</li>
        <li><span>Comments:</span> ${c}</li>
        <li><span>Downloads:</span> ${q}</li>
      </ul>
    </div>
  </li>`).join("")}function M(e){e.innerHTML=""}function b(e,r){e.insertAdjacentHTML("beforeend",r)}const g=document.querySelector("#search-form"),f=document.querySelector(".gallery"),u=document.querySelector("#load-more"),h=document.querySelector(".loader");let m="",a=1;const p=150;let y=0,v=new R(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});l();d();g.addEventListener("submit",async e=>{e.preventDefault();const r=g.elements.query.value.trim();if(r===""){n.warning({title:"Warning",message:"Please enter a search query",position:"topRight"});return}m=r,a=1,M(f),l(),S();try{const i=await L(m,a,p);if(d(),y=i.totalHits||0,!i.hits||i.hits.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const s=w(i.hits);b(f,s),v.refresh(),a*p<y?P():(l(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{d(),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}});u.addEventListener("click",async()=>{a+=1,l(),S();try{const e=await L(m,a,p);if(d(),!e.hits||e.hits.length===0){n.info({title:"No more",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l();return}const r=w(e.hits);b(f,r),v.refresh(),O(),a*p<e.totalHits?P():(l(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{d(),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}});function S(){h&&h.classList.remove("hidden")}function d(){h&&h.classList.add("hidden")}function P(){u&&u.classList.remove("hidden")}function l(){u&&u.classList.add("hidden")}function O(){const e=f.querySelector(".photo-card");if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
